### ISSUE TITLE
When too many blocks are loaded my server crashes!

### ISSUE THREAD

**Issue by iSilviu-debug** [tr7zw/YAPFA#215] opened 2020-09-28 20:31 UTC
**Expected behavior**
Chunk to load normally.

**Observed behavior**
https://pastebin.com/1LKvSXHv
Server crashes when too many blocks get loaded in a chunk.

**Steps to reproduce (if known)**
Plugins or structures that load not very fast but for example 9 chunks per second

**Installed plugins**
Plugins (66): AntiAutoCannon*, AntiCooldown, AutoBroadcast, BlowableObsidians, BuycraftX, CannonFix*, ChatControl, ChorusFruit, CMI, CMIEInjector*, CMIPaperLib, CombatLogX, ConditionalCommands*, CoreProtect, CrazyAuctions, Drycell, Envoys, Factions, FactionsRoster*, FactionsTop, FactionsTopv5Hologram, FastAsyncWorldEdit, FeatherBoard*, FishRodFix, FogusCore, GoldenCrates, HolographicDisplays, HolographicExtension, InventorySaver, ItemSoulBind, LuckPerms, mcMMO, MVdWPlaceholderAPI*, Netherportals, NoBedExplosions, Nobreakspawner, NoCheatPlus, NotchAppleCrafter*, ObsidianBreaker, Outpost*, PlaceholderAPI, PlugMan, PrinterMode, PvPLevels, SAML, Scyther, ServerNPC, ServerTutorialPlus*, ShopGUIPlus, SimplePortals, spark, SpigotGuard, SSX-Connector*, TAB, TerraformGenerator, TNTFill*, UltraRegions, Vault, VoidGenerator, WildApi, WildBuster, WildStacker, WildTools, WorldBorder, WorldEdit, WorldGuard
*Many don't work due to updates, I have yet to fix*

**Version**
git-Yatopia-"56cfcf9" (MC: 1.16.3)

**Comment by iSilviu-debug** [comment] 2020-09-29 06:06
I tried a more thorough test and went to try the same chunk load with Yatopia, Tunity and Paper. The only one who doesn't crash is Paper, while Tunity and Yatopia do.

**Comment by MrIvanPlays** [comment] 2020-09-29 06:54
we will try to fix it on our own and if it works we will backport it to tuinity if it comes from them

**Comment by MrIvanPlays** [comment] 2020-09-29 09:58
Can u reproduce on latest? I see you are 18 versions behind

**Comment by iSilviu-debug** [comment] 2020-09-29 10:08
ok, exact download link?

**Comment by MrIvanPlays** [comment] 2020-09-29 10:10
https://ci.codemc.io/job/YatopiaMC/job/Yatopia/job/ver%252F1.16.3/

**Comment by iSilviu-debug** [comment] 2020-09-29 11:36
A friend of mine tested the fact with the latest version and it doesn't seem to crash, I still have to try it for good; however a plugin named wildstacker when it has to spawn a mob or an object gives error while with tunity / paper it works correctly. Why? 
**Error**
https://pastebin.com/PEuw1z3Q

**Comment by MrIvanPlays** [comment] 2020-09-29 11:38
We cant tell exactly why that error with WildStacker occurs, the author of the plugin should get in touch with us so we know if it is a plugin issue or our issue. 
Additionally, mob stacker plugins aren't recommended.

Closing as cannot reproduce.

**Closed as completed by MrIvanPlays** 2020-09-29 11:38 UTC
Labels: bug

**Comment by iSilviu-debug** [comment] 2020-09-29 11:39
Wildstacker is a partial use of spawners that are stacked not just mobs

**Comment by iSilviu-debug** [comment] 2020-09-29 11:40
However I believe it is a NMS problem for later versions. Thanks for your support, see you again!
