### ISSUE TITLE
Server Crashing because out of memory error

### ISSUE THREAD

**Issue by Hellohi3654** [tr7zw/YAPFA#254] opened 2020-10-14 10:23 UTC
**Expected behavior**
 
Server not to crash
**Observed behavior**

Hi I need some help
I have my startup flags set to this:

java -Xms4000M -Xmx4000M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs/ -Daikars.new.flags=true -jar server.jar
but I'm getting a out of memory error every 5 hours or so
and the server restarts
**Steps to reproduce (if known)**

Set server to those flags and run
wait about 5 hours then the server gets a out of memory error and restarts
**Installed plugins**

![image](https://user-images.githubusercontent.com/57390764/95976439-39405280-0e63-11eb-806e-c1cc3da91363.png)

**Version**

![image](https://user-images.githubusercontent.com/57390764/95976465-452c1480-0e63-11eb-9c0d-815e9cb9feff.png)

**Timings**

https://timings.aikar.co/?id=09e7b5357f81443fbbbb56eceee6cd65

**Additional context**

**Comment by metabrixkt** [comment] 2020-10-14 10:42
**Not related directly to this issue**, but I was using EntityTrackerFixer, PlugMan and VilalgerOptimiser, Yatopia devs asked me to remove them, because:
1. Entity tracker is already good on yatopia, and as far as I know it's async.
2. PlugMan: 99% of plugins don't disable properly, you should use PlugMan **only for testing** and not on production server.
3. Villagers are already optimized on Yatopia.

Also as I see GriefPreventionDynmap's tasks cause lags.

If you use java 8, I suggest you using java 11 or 14. And if possible, allocate more memory to the server (I think 8G could be ok).

**Comment by Hellohi3654** [comment] 2020-10-14 10:44
I can't allocate more memory to the server but I can remove those plugins

**Comment by Hellohi3654** [comment] 2020-10-14 10:44
also thanks

**Comment by MrIvanPlays** [comment] 2020-10-14 12:55
4 GiB ( and particularly everything under 6 GB ) is not enough for a production server. Additionally this is a duplicate of https://github.com/PaperMC/Paper/issues/4288 but the not much memory just sped up the crash.

**Closed as completed by MrIvanPlays** 2020-10-14 12:55 UTC
