### ISSUE TITLE
PlayerDeathEvent.getDeathMessage adds needless chat color symbols  

### ISSUE THREAD

**Issue by fulcanelly** [tr7zw/YAPFA#387] opened 2021-02-03 01:24 UTC
**Expected behavior**
PlayerDeathEvent.getDeathMessage() -> "{player name} {death reason}"

**Observed behavior**
PlayerDeathEvent.getDeathMessage() -> "§f§f{player name}§f {death reason}"

**Steps to reproduce**
Just write casual plugin(with 1.16 API version) which listens to PlayerDeathEvent and prints result of getDeathMessage method call and then die somehow on the server: 
```java
class Plugin extends JavaPlugin implements Listener {

     @EventHandler
     void onPlayerDeathEvent(PlayerDeathEvent event) {
         //raplace is needed since outputstream can hine from us where § was 
         getLogger().info(event.getDeathMessage().replace("§", "?????"));
     }

    @Override 
    void onEnbale() {
        getServer().getPluginManager()
              .registerEvents(this, this);
    }

}

```
**Installed plugins**
Only described above  

**Version**
[01:12:18 INFO]: This server is running Yatopia version git-Yatopia-staging/1.16.5-26 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[01:12:18 INFO]: Previous version: git-Paper-444 (MC: 1.16.5)
[01:12:18 INFO]: You are running the latest 

**Additional context**
Everything works fine as expected with paper but when run this on yatopia such stuff happens, so probably problems on some of API patches

**Comment by fulcanelly** [comment] 2021-02-03 01:31
fixed formatting problems

**Comment by ishland** [comment] 2021-02-04 10:48
Can you try reproduce this on Purpur?

**Comment by fulcanelly** [comment] 2021-02-07 01:26
I tried, same problem

**Comment by Titaniumtown** [comment] 2021-02-09 15:49
Can this be reproduced on Paper? If so, please report there.

**Comment by Titaniumtown** [comment] 2021-02-09 15:51
Since this is reproducible on Purpur. Please report that there. I'm closing this in favor of an issue being opened on Purpur's github instead.

**Closed as completed by Titaniumtown** 2021-02-09 15:51 UTC
Labels: bug, upstream/sidestream, low priority
