### ISSUE TITLE
Lots of threads

### ISSUE THREAD

**Issue by iAverages** [tr7zw/YAPFA#280] opened 2020-11-06 16:30 UTC
Hi, I've been having some issues recently with a server either crashing due to watchdog or getting stuck for a bit then coming back (Both due to the main thread getting stuck). I had a friend who is more experienced with java help me out and we used yourkit java profiler to try and find the issue. He said that the server has way to many threads running (1000+) and that that's likely the reason why the server has been crashing (He said most are from bukkit). He also said that the issue is likely a server jar issue and recommened that I opened an issue about it. 

![img](https://cdn.discordapp.com/attachments/672079951008235541/774295887722577940/unknown.png)

**Observed behavior**

Way to many threads on the server (Craft scheduler thread) on the server.

**Installed plugins**

___removed___

**Version**

![version](https://dannn.net/ikihbQIo)

**Timings**

https://timings.aikar.co/?id=2936985645cc4a0ebe83911843b0ceb2

**Comment by metabrixkt** [comment] 2020-11-06 16:35
I'm not sure is it directly related to the issue, but Yatopia developers **highly recommend** removing _EntityTrackerFixer_, _PlugMan_ and _VillagerOptimiser_ since they aren't good for using on production server.
1. Entity tracking is already good on Yatopia.
2. 99% of plugins doesn't disable properly, it must NOT be used on production server, like /reload.
3. It worked good on 1.15, but on 1.16 it's bad.

**Comment by iAverages** [comment] 2020-11-06 17:02
Plugman is very very rarely used. I only use it on plugins I know work. (Even then we try to restart if possible).
I'll try removing the other 2 plugins.

**Comment by metabrixkt** [comment] 2020-11-06 17:05
Ok, I think (not sure) you can use plugman if you 100% sure these plugins work properly with plugman.

**Comment by toinouH** [comment] 2020-11-06 17:07
Hello

1. If you could provide logs of the crash it would be super cool to get this ^^

2. If you friend wish to help us to he can join Discord and discuss with us

**Comment by iAverages** [comment] 2020-11-06 17:18
#269 has a list of thread dumbs (most are crashes, server killed by watchdog) Not sure if these are relevant to this issue. 

We check when the server froze for a bit. I've included a thread dump and a screenshot of yourkit
![yourkit](https://dannn.net/BQ94Vzae)
https://paste.danielraybone.com/zudabizupe.hs

**Comment by ishland** [comment] 2020-11-06 22:25
Seems like a plugin is doing something. Probably check your plugin first.

**Comment by MrIvanPlays** [comment] 2020-11-08 17:23
Craft scheduler threads are the threads where plugins execute asynchronous tasks using the bukkit api. The pool won't make that many threads unless it is forced to. Either way these threads have a `keepAlive` time of 30 seconds, and if any is found unused it is terminated after x time ( x time being no more than the `keepAlive` of the thread created ). 

Your friend has no in-depth experience in java. Thread count doesn't matter at all, unless you have bad cpu. 
If you experience any more crashes, please open a new issue with a full watchdog dump and/or a crash dump. 

Closing as not a bug.

**Closed as completed by MrIvanPlays** 2020-11-08 17:23 UTC
Labels: not a bug
