### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by nullexcept1on** [tr7zw/YAPFA#171] opened 2020-08-28 23:49 UTC
## Expected behavior
Shulker should be placed at 255 height without kick from the server. And when the shulker is opened at 255 height, the server is closed.

## Observed behavior
The server crashed

## Steps to reproduce
Just start the server, place shulker box in 255 height and open him.
**Installed plugins:** No plugins
**Java:**
```
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
```
**Yatopia:** https://github.com/YatopiaMC/Yatopia/releases/tag/1.16.2 (Yatopia-1.16.2-JDK14-paperclip.jar)
Any version contains this bug. Tested at https://github.com/YatopiaMC/Yatopia/actions/runs/229054735 and https://github.com/YatopiaMC/Yatopia/releases/tag/1.16.2

## Version
```
[22:34:07 INFO]: This server is running Yatopia version git-Yatopia-"2e45651" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
```

## Crash

**Crashlog:** https://pastebin.com/m6vkrEk1
**Error from console:**
```
[22:34:25 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_16_R2.ReportedException: Exception ticking world
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1445) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:396) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1277) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:165) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.updateState(BlockBase.java:616) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.a(BlockBase.java:546) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.a(BlockBase.java:531) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.TileEntityShulkerBox.x(TileEntityShulkerBox.java:206) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.TileEntityShulkerBox.setProperty(TileEntityShulkerBox.java:196) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.BlockTileEntity.a(SourceFile:29) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.a(BlockBase.java:523) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:2246) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.WorldServer.aj(WorldServer.java:2236) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:904) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1429) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        ... 5 more
[22:34:25 ERROR]:       Cause of unexpected exception was
java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.updateState(BlockBase.java:616) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.a(BlockBase.java:546) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.a(BlockBase.java:531) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.TileEntityShulkerBox.x(TileEntityShulkerBox.java:206) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.TileEntityShulkerBox.setProperty(TileEntityShulkerBox.java:196) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.BlockTileEntity.a(SourceFile:29) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.a(BlockBase.java:523) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:2246) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.WorldServer.aj(WorldServer.java:2236) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:904) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1429) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:396) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1277) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:165) ~[patched_1.16.2.jar:git-Yatopia-"2e45651"]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by toinouH** [comment] 2020-08-28 23:54
Can you confirm this with paper if yes can you confirm this with spigot too ?

**Comment by nullexcept1on** [comment] 2020-08-29 00:49
I'm testing on [paper](https://papermc.io/api/v1/paper/1.16.2/158/download) and [spigot through BuildTools](https://www.spigotmc.org/wiki/buildtools/#1-16-2).

No crash

**Comment by MrIvanPlays** [comment] 2020-08-29 07:46
duplicate of #165

**Closed as completed by MrIvanPlays** 2020-08-29 07:46 UTC
