### ISSUE TITLE
TNT flies through the closed gate

### ISSUE THREAD

**Issue by dalandis** [tr7zw/YAPFA#251] opened 2020-10-11 16:18 UTC
**Expected behavior**
A closed gate does not allow TNT to pass

**Observed behavior**
TNT flies through the closed gate

**Steps to reproduce (if known)**
https://www.youtube.com/watch?v=E0qpkDeyJlc&feature=youtu.be
Just put TNT on the gate and set it on fire

**Installed plugins**
> plugins 
[19:16:08 INFO]: Plugins (13): ACNotify*, Chunkmaster, CMI, CMIPaperLib, (WorldEdit)FastAsyncWorldEdit, LogBlock, LuckPerms, NoMobGriefing, PlaceholderAPI, PlotSquared, ProtocolLib, Spartan, UltraRegions

**Version**
> version
[19:16:28 INFO]: This server is running Yatopia version git-Yatopia-"eb35761" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[19:16:28 INFO]: Checking version, please wait...
[19:16:28 INFO]: Previous version: git-Yatopia-"252bf7e" (MC: 1.16.3)
[19:16:28 INFO]: You are 2 version(s) behind

**Timings**
https://timings.aikar.co/?id=02ea5f44427d4fba92a7b88e6c27961b

**Comment by MrIvanPlays** [comment] 2020-10-12 16:18
That's a bug with the async entity tracking if I had to guess. We dropped that patch recently so updating to latest will fix your issue. Im not gonna close it as we plan on readding that patch in the future.

**Comment by dalandis** [comment] 2020-10-13 09:12
For build 119, the problem is relevant.
https://www.youtube.com/watch?v=NbASjiQVzq4

> version
[12:00:17 INFO]: This server is running Yatopia version git-Yatopia-"0a2b893" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[12:00:17 INFO]: Checking version, please wait...
[12:00:18 INFO]: Previous version: git-Yatopia-"eb35761" (MC: 1.16.3)
[12:00:18 INFO]: You are running the latest version

**Comment by MrIvanPlays** [comment] 2020-10-13 09:16
can u try without plugins and on tuinity/paper too

**Comment by dalandis** [comment] 2020-10-13 09:21
No problem. But in the evening.

**Comment by dalandis** [comment] 2020-10-13 14:00
with plugins:
yatopia - not working
paper - working
tuinity - working

without plugins:
yatopia - not working
paper - working
tuinity - working

Everything has been updated to the latest versions

**Comment by MrIvanPlays** [comment] 2020-10-18 16:22
after further investigation this is normal vanilla behavior. or if its not intended vanilla behavior then it is a vanilla bug, but i'd say its intended behavior cuz i turned mojira upside-down to search for such issue, and didn't found anything, plus tnts are known to fall off of some blocks.

**Closed as completed by MrIvanPlays** 2020-10-18 16:22 UTC
Labels: bug, good first issue, normal priority

**Comment by MrIvanPlays** [comment] 2020-10-18 16:28
also a video to confirm my words
https://streamable.com/ya2mxo

**Comment by dalandis** [comment] 2020-10-19 05:11
I'll do additional checks, but I'm sure the problem is
exists

**Comment by dalandis** [comment] 2020-10-19 21:35
It turned out the following.
TNT should be thrown onto the gate, not set.

And that the problem was related to the chunk or blocks in the chunk and manifests itself only in Yatopia. The mechanism was transferred to a neighboring chunk and it began to work perfectly.

I selected the gate with the WE and made //regen, after which I returned the gate back. As a result, the mechanism works perfectly.
