### ISSUE TITLE
IllegalArgumentException Entering nether portal

### ISSUE THREAD

**Issue by ishland** [tr7zw/YAPFA#151] opened 2020-08-25 02:29 UTC
**Expected behavior**
Enter the nether normally

**Observed behavior**
Enter the nether and kicked the player and crash the server.

**Steps to reproduce (if known)**
1. Enter the nether portal
2. Server kicked the player
3. Server crash

**Installed plugins**
```
Plugins (22): Barrels, BiomeIDFix, CS-CoreLib, JukeBox, MinecraftSP, MineTinker, MultiverseteBlockAPI, PlaceholderAPI, PluginManager*, ProtocolLib, QQMinecraft*, SandtoQuartz, ServerMSPT, Slimefun, sleManager*, Vault, ViaBackwards, ViaVersion, WorldEdit, XPConomy
```

**Version**
```
This server is running Yatopia version git-Yatopia-"e1a085d" (MC: 1.16.2) (Implementing API1.16.2-R0.1-SNAPSHOT)
```

**Additional context**
Server log: https://paste.ubuntu.com/p/vP7VS2r9mN/

**Comment by Titaniumtown** [comment] 2020-08-25 03:28
Wasn't the BiomeIDFix stuff added into yatopia? Correct me if I'm wrong.

**Comment by ishland** [comment] 2020-08-25 03:30
Everything commented here should be related to the issue. Please go to discord to talk about this.

**Comment by Titaniumtown** [comment] 2020-08-25 03:31
wdym? I was just thinking that BiomeIDFix could be conflicting with yatopia or something :shrug:

**Comment by ishland** [comment] 2020-08-25 03:38
This doesn't conflicts with Yatopia and it works fine for me. This was integrated into Yatopia but removed later.

**Comment by Titaniumtown** [comment] 2020-08-25 03:38
Oh ok, thanks for the clarification.

**Comment by Titaniumtown** [comment] 2020-08-25 03:39
I'm thinking this is a plugin issue. hmmm

**Comment by ishland** [comment] 2020-08-25 03:41
Cannot get reproduced again since i crashed my server for about 15 times. It appears to be random

**Comment by MrIvanPlays** [comment] 2020-08-25 08:08
Cannot reproduce on both e1a085d and 78c24fd

**Comment by ishland** [comment] 2020-08-25 10:56
Also cannot get reproduced for me but it is purely random

**Comment by MrIvanPlays** [comment] 2020-08-25 17:54
closing due to cannot reproduce repeatedly.

**Closed as completed by MrIvanPlays** 2020-08-25 17:54 UTC
Labels: bug, normal priority, cannot reproduce
