### ISSUE TITLE
Horses jumping like crazy when near fences

### ISSUE THREAD

**Issue by ghost** [tr7zw/YAPFA#274] opened 2020-10-29 13:35 UTC
**Expected behavior**
Not to jump like crazy near fences

**Observed behavior**
When horses are near fences they are jumping and phasing through fences

**Steps to reproduce (if known)**
Put a horse in a 5x5 fence area then wait for the horse to start phasing through and jumping

**Installed plugins**
No plugins

**Version**
![Capture](https://user-images.githubusercontent.com/69083497/97580488-4759ab80-19eb-11eb-9562-67855766d55b.PNG)

**Additional context**
It is also happening with Donkeys (Not sure about other mobs)

**Comment by MrIvanPlays** [comment] 2020-10-29 13:35
Duplicate of #216

**Closed as completed by MrIvanPlays** 2020-10-29 13:35 UTC
Labels: duplicate
