### ISSUE TITLE
Enderman not triggering

### ISSUE THREAD

**Issue by NovaPixell** [tr7zw/YAPFA#7] opened 2020-05-05 15:08 UTC
Hi, I'm really happy with the optimizations of your software. Only thing, endermans stay freeze when they see endermite, so enderman farms don't work. How can I do?
Also I want to ask you, do you have a wiki where you explain all the configurable values?
I also wanted to ask you, do your builds include the latest version of paper? Do they update themselves?

**Comment by tr7zw** [comment] 2020-05-05 15:14
Yea documenting everything is defenitly something I'll do. I'll have to check why enderman don't react to endermite, but I'd think that's an upstream problem (probably). Also yes it should be fairly up to date to Tuinity and therefor as up tp date to Paper as Tuinity is.

**Comment by NovaPixell** [comment] 2020-05-05 15:20
Okok thanks, please try to solve this enderman problem as I have a big vanilla server .. in short, there is a lot of need haha. For a better optimization, what do you recommend to edit in the configurations? Also in tuinity.yml there is the option "no-tick-view-distance: -1", what is it for? I set view distance on server.properties 5, can the option in tuinity.yml increase the viewing distance without loading those chunks?

**Comment by tr7zw** [comment] 2020-05-05 15:37
For the tuinity settings check out their discord, regarding yapfa settings for a vanilla server I'd say:
disablePlayerOutOfWorldBorderCheck true
disableEntityCollisions true (when possible)
disableEntityCollisionboxes true
onlyPlayerCollisions true (2nd option when not disable all EntityCollisions)

Most other optimizations are always enabled since they don't change the vanilla behavior.

**Comment by NovaPixell** [comment] 2020-05-05 15:45
thx!

**Comment by NovaPixell** [comment] 2020-05-05 19:18
I saw that you released a new build, but I see that endermans have the same problem :/

**Comment by tr7zw** [comment] 2020-05-05 20:28
Yea that was just an upstream update. Check with Tuinity if the same behavior occurs there since I don't think I touched anything that should modify how enderman behave.

**Comment by NovaPixell** [comment] 2020-05-05 20:38
Okay do we have to wait for an update of Tuinity?

**Comment by tr7zw** [comment] 2020-05-05 22:02
https://tr7zw.dev/u/1588716000.jpg Ok just tested it and this bug is also on Tuinity/Paper, so that's an upstream problem. Might also need to check Spigot and then open the issue at the correct project.

**Comment by NovaPixell** [comment] 2020-05-05 22:23
Okay, update me if there are news .. Also because it is a bit serious

**Comment by tr7zw** [comment] 2020-05-05 22:46
Ok update: after testing in singleplayer it turns out that the wiki is wrong. Endermites spawned from enderpearls do correctly get attacked by enderman on yapfa (https://tr7zw.dev/u/1588718645.png), but even in singleplayer enderman don't care for endermites spawned with an spawnegg (https://tr7zw.dev/u/1588718724.png), making the wikis statement ``Endermen attempt to kill endermites that spawn from ender pearls and endermites that are spawned from spawn eggs. `` wrong.

**Comment by NovaPixell** [comment] 2020-05-05 22:51
Wait up. But look at the fact that the endermites are spawned in survival. In fact, the endermans get angry. Only that they remain freezed. Maybe tomorrow I'll turn a screen

**Comment by tr7zw** [comment] 2020-05-05 22:52
Odd. The ones I spawned got quickly killed by the enderman. Maybe some plugin issue preventing the enderman from porting?

**Comment by NovaPixell** [comment] 2020-05-05 22:55
Exactly, I removed all the plugins like entitytrackerfixer and saml but the problem still arises

**Comment by tr7zw** [comment] 2020-05-05 22:59
So far I wasn't able to reproduce any difference to vanilla singleplayer. Just noticed that enderman will not use teleports to attack the endermite https://tr7zw.dev/u/1588719463.jpg. So yea, they get aggressive, will walk to the endermite when possible, so without a screen or something I can't see anything wrong?

**Comment by NovaPixell** [comment] 2020-05-05 23:07
@
Look here. Endermans are freezed

**Comment by tr7zw** [comment] 2020-05-05 23:24
[2020-05-06_01-22-45.zip](https://github.com/tr7zw/YAPFA/files/4584134/2020-05-06_01-22-45.zip)

Just built a quick enderman farm and yea it works. Pretty sure the design is broken that the enderman can't pathfind to the endermite because of missing space.

**Comment by NovaPixell** [comment] 2020-05-05 23:30
Ah...

**Comment by NovaPixell** [comment] 2020-05-06 09:38
Ok fixed! Apparently the design we had only worked on paper .. bah ahah thanks again!

**Comment by tr7zw** [comment] 2020-05-06 15:48
Well gonna close this. Couldn't find any testable difference to vanilla and I mean, it works sooo^^

**Closed by tr7zw** 2020-05-06 15:48 UTC
Labels: bug, enhancement, question
