### ISSUE TITLE
Entity Collision FIlter does not work (1.16.1)

### ISSUE THREAD

**Issue by NovaPixell** [tr7zw/YAPFA#143] opened 2020-08-22 10:15 UTC
**Expected behavior**
The Entity Collision FIlter does not work

**Observed behavior**
If you try to disable collisions on one of the entries in the yatopia.yml file, they will collide anyway.

**Steps to reproduce (if known)**
In my case, I have disabled collisions for "animals", "pillager" and "water-animals".
https://gyazo.com/bb5da63d2ead10e98aeb3a102f63458c

As you can see, these suffer from collisions
https://gyazo.com/5b999d5ee04ea6bdb74752caf597dc64

**Installed plugins**
https://gyazo.com/f1a677ccd3b38dc67a558c8e6d3f34dc

**Version**
git-Yatopia-c692d26 (1.16.1)

**Comment by MrIvanPlays** [comment] 2020-08-22 11:07
alright, before closing I need to say something. if you're shift clicking it won't disable collisions. we can't change that behavior

Here's builds you can try: [1.16.1](https://github.com/YatopiaMC/Yatopia/actions/runs/219624639) and [1.16.2](https://github.com/YatopiaMC/Yatopia/actions/runs/219621360)

**Comment by NovaPixell** [comment] 2020-08-22 12:30
the problem still occurs with build d06e04f. No, I don't use shift while moving entities, I just tried now

**Comment by MrIvanPlays** [comment] 2020-08-22 12:54
I cannot reproduce with d06e04f

show us ur configs.

**Comment by NovaPixell** [comment] 2020-08-22 13:08
Oh very strange... 

yatopia config: https://pastebin.com/hT4MGuNt

**Comment by MrIvanPlays** [comment] 2020-08-22 13:13
set `disableEntityCollisionboxes` to false and try again

**Comment by NovaPixell** [comment] 2020-08-22 13:20
ok I'll let you know!

**Comment by NovaPixell** [comment] 2020-08-22 13:32
same problem... strange...

**Comment by MrIvanPlays** [comment] 2020-08-24 08:48
Closing due to no activity & no one else reporting to reproduce.

**Closed as completed by MrIvanPlays** 2020-08-24 08:48 UTC
Labels: bug, high priority, cannot reproduce

**Comment by NovaPixell** [comment] 2020-08-24 08:57
I said I still have the problem

**Comment by MrIvanPlays** [comment] 2020-08-24 08:59
Only you. No one else.
Search for the problem in your configurations.

**Comment by NovaPixell** [comment] 2020-08-24 09:00
Do I try to regenerate the yatopia file?

**Comment by NovaPixell** [comment] 2020-08-24 10:19
Now I have created a new server with these settings, on the build git-Yatopia- "d06e04f. And the entities still suffer from collisions. So it's not my problem. Specifically, I use it in 1.16.1.

     collisions:
       players: true
       animals: false
       ambient: false
       monsters: true
       villagers: true
       pillagers: false
       iron-golems: true
       misc: true
       items: true
       water-creature: false
       water-ambient: false
