### ISSUE TITLE
Plugins are crashing everytime i start the server.

### ISSUE THREAD

**Issue by Shurelia** [tr7zw/YAPFA#422] opened 2021-02-23 17:17 UTC
**Expected behavior**
 
server and plugins starts normally.

**Observed behavior**

instead of loading it, almost every plugins somehow failed to load and disables itself.

**Steps to reproduce (if known)**

starting the server for my first experience on yatopia and boom, every plugins is crashing.

**Installed plugins**

![image](https://user-images.githubusercontent.com/33577181/108880792-35081b00-7635-11eb-90a4-fe4fcb117923.png)

**Version**

![image](https://user-images.githubusercontent.com/33577181/108880866-46e9be00-7635-11eb-9bdc-0309a74fa5f9.png)

**Additional context**

logs: https://pastebin.com/GE1qUzwB

**Comment by michitta** [comment] 2021-02-23 17:32
What version of java are you using?

**Comment by Shurelia** [comment] 2021-02-23 17:45
debian_openjdk-11

**Comment by Shurelia** [comment] 2021-02-23 17:45
> What version of java are you using?

java 11, debian_openjdk-11

**Comment by michitta** [comment] 2021-02-23 17:51
> > What version of java are you using?
> 
> java 11, debian_openjdk-11

try java 15

**Comment by TheDGOfficial** [comment] 2021-02-23 17:59
It has something to do with Javaassist, are you have any plugins that shade
it?

**Comment by Shurelia** [comment] 2021-02-23 18:11
> > > What version of java are you using?
> > 
> > 
> > java 11, debian_openjdk-11
> 
> try java 15

okay ill try it later, but isnt some plugins still doesnt have support for 15?

> It has something to do with Javaassist, are you have any plugins that shade it?

no idea, before i was using purpur and everything works normally
didnt know if its because one of my plugins tho, could you tell me wich plugin that might be causing it?

**Comment by TheDGOfficial** [comment] 2021-02-23 23:07
It might be the yatopia too if it doesn't occur on purpur, but something is rewrting alll of the plugins bytecode and adding classes ending with L10 to them with a shaded & obfuscated javassist library (suspicious & weird) and that is causing errors. If you use any leak/cracked premium plugins, remove them.

For resolving the errors if you use legitimate versions and/or stuck with a leak/crack one and want to just get rid of errors, maybe also try with tuinity and/or other software that yatopia pulls patches from to see if it is reproducible on them or if it only occurs on yatopia.

Looking at the logs, it is probably LiteBans or FastAsyncWorldEdit:
`[01:12:11] [Server thread/WARN]: [FastAsyncWorldEdit] Loaded class javassist.bytecode.u from LiteBans v2.5.9 which is not a depend, softdepend or loadbefore of this plugin.`

This the first occurence of javassist in the logs, so it is probably either LiteBans or FastAsyncWorldEdit _that cause the error_, but even if they cause, not sure why it doesn't happen on purpur.

Java access system has nothing to do with server software, that should give IllegalAccessException on all programs in all Java versions (though it can give different error since module system is added in Java 9+) if a class tries to access a protected method from different package. (javassist.bytecode.r trying to access java.assist.bytecode.u)

**Comment by a8underscore** [comment] 2021-02-24 03:45
try removeing all plugins, and adding one plugin back at a time, and see if a specific plugin is causeing the issues

**Comment by Shurelia** [comment] 2021-02-24 06:11
> It might be the yatopia too if it doesn't occur on purpur, but something is rewrting alll of the plugins bytecode and adding classes ending with L10 to them with a shaded & obfuscated javassist library (suspicious & weird) and that is causing errors. If you use any leak/cracked premium plugins, remove them.
> 
> For resolving the errors if you use legitimate versions and/or stuck with a leak/crack one and want to just get rid of errors, maybe also try with tuinity and/or other software that yatopia pulls patches from to see if it is reproducible on them or if it only occurs on yatopia.
> 
> Looking at the logs, it is probably LiteBans or FastAsyncWorldEdit:
> `[01:12:11] [Server thread/WARN]: [FastAsyncWorldEdit] Loaded class javassist.bytecode.u from LiteBans v2.5.9 which is not a depend, softdepend or loadbefore of this plugin.`
> 
> This the first occurence of javassist in the logs, so it is probably either LiteBans or FastAsyncWorldEdit _that cause the error_, but even if they cause, not sure why it doesn't happen on purpur.
> 
> Java access system has nothing to do with server software, that should give IllegalAccessException on all programs in all Java versions (though it can give different error since module system is added in Java 9+) if a class tries to access a protected method from different package. (javassist.bytecode.r trying to access java.assist.bytecode.u)

ah yea, just tested it with spigot's anti malware resource and they're all got infected with something called L10, i've removed that kind of thing before by redownloading all of the plugins but i have no idea how it could go back to infect my plugins (i didnt use any kind of leaked plugins either) also did you know what L10 do to my server except making my plugins failed to load on yato? 

also i'll try redownloading all of my plugins again later, and ill say something in here if it fixes my problem, thank you so much!.

**Closed as completed** 2021-02-24 18:27 UTC

**Comment by Shurelia** [comment] 2021-02-24 18:30
after redownloading all of my plugins everything works normally as expected! thank you guys for helping me solve this issue <3

**Comment by Sculas** [comment] 2021-04-26 23:37
That malware is a backdoor.
