### ISSUE TITLE
Boat Bug

### ISSUE THREAD

**Issue by AsrielDewitt** [tr7zw/YAPFA#188] opened 2020-09-05 01:33 UTC
**Expected behavior**
Fall off boat normally

**Observed behavior**
snapping back to the boat, unable to fallof

**Steps to reproduce (if known)**
exit the boat and just press w. 

**Installed plugins**
Non

**Version**
1.16.2

**Comment by MrIvanPlays** [comment] 2020-09-05 04:53
known issue on tuinity’s end, leaf is currently testing a fix

**Comment by AsrielDewitt** [comment] 2020-09-05 04:54
This is also happened on Paper. Try leaving a boat with 200ms ping

**Comment by MrIvanPlays** [comment] 2020-09-05 04:56
200ms is not normal ping. This means you have network lag. Yet this issue is still valid tho. Everything above 100ms is unplayable

**Comment by AsrielDewitt** [comment] 2020-09-05 04:57
wut? 200ms playable, just have to adapt to it. Beside, this is minecraft, why would you need super low ping?

**Comment by duplexsystem** [comment] 2020-09-05 04:58
Regardless you said it also happened on paper. It's not our bug then.

**Comment by AsrielDewitt** [comment] 2020-09-05 04:59
Would that fix on Paper even reach Yatopia? And this bug happened a long time now. Even on 1.8 (i think)

Yet nobody fixed it

**Comment by MrIvanPlays** [comment] 2020-09-05 05:00
mojong patched it in 1.13 yet smh it is bacc

**Comment by duplexsystem** [comment] 2020-09-05 05:00
If paper fixes it we will have it with in days. We do constant upstream updates.

**Comment by duplexsystem** [comment] 2020-09-05 05:00
I'd no one has any objections I'm closing the issue.

**Comment by AsrielDewitt** [comment] 2020-09-05 05:00
How is it back anyway? How did this bug even worked?

**Comment by MrIvanPlays** [comment] 2020-09-11 18:19
I was able to reproduce on vanilla 1.16.3 once, but I wasn't able to reproduce it on yatopia 1.16.3
This is a rare case vanilla issue.

**Comment by AsrielDewitt** [comment] 2020-09-11 21:24
Recreating is easy.....just hold w to walk off with ping around 150 or 200.

And Rare Case? This happened to me every single time trying to get off a boat.

It's to the point I instinctively strafe jump off a boat to avoid it

**Comment by MrIvanPlays** [comment] 2020-09-12 04:53
then what you’re experiencing is network lag. so we can say that it gets more serious with ping above 100

**Comment by MrIvanPlays** [comment] 2020-09-13 17:26
![image](https://img.mrivanplays.com/msedge_YWpBLSTq8D.png)

**Comment by AsrielDewitt** [comment] 2020-09-13 21:38
I disagree that rate very much. Well, the not the first 2

1-90= Best!
91-179= Great
180-299= Good
300-499= poor
500+= Find a server close to you


Again, this is Minecraft, you don't need to have super low ping rate to play the game normally.
If you're a hardcore player, that do super fast PvP or something alike

but for anybody who just wanna play normal survival or creative
anything below 300ping is good enough to play without getting annoying.

**Comment by MrIvanPlays** [comment] 2020-09-14 04:51
yes minecraft is tcp but that doesnt mean high ping is ok.

**Comment by AsrielDewitt** [comment] 2020-09-14 05:49
Yes, I get that

High enough ping, the game feels annoying to play. But that limit is usually at 300+

Below that. It's good enough for any casual play.

**Comment by MrIvanPlays** [comment] 2020-09-14 05:52
> It's good enough for any casual play.

no its not lol. just because you got used to it doesn't mean others will.

**Comment by MrIvanPlays** [comment] 2020-09-15 07:33
closing due to networking issue.

**Closed as completed by MrIvanPlays** 2020-09-15 07:33 UTC
Labels: bug, vanilla, rare case reproduce, network issue
