### ISSUE TITLE
Advancements sometimes reset

### ISSUE THREAD

**Issue by metabrixkt** [tr7zw/YAPFA#172] opened 2020-08-29 09:58 UTC
**Expected behavior**
Everyone can play like normal and get advancements.

**Observed behavior**
Everyone can play like normal, but sometimes players who played a lot (it hasn't happened with newbies yet) get an advancements reset.

**Steps to reproduce (if known)**
I don't really know what causes this and how can it be reproduced. The only details I know are: people it happened with had all or almost all advancements; I got advancement reset when I relogged quickly (disconnected and immediately reconnected)

**Installed plugins**
No plugins. It has happened one time on my second server which hasn't any plugins.

**Version**
I don't use this version, but it was git-Yatopia-"c692d26" 1.16.1 JDK8, downloaded from Releases on github.

**Additional context**
async-advancements is false

EDIT: It happened 4 minutes ago with one more player when they quickly disconnected and reconnected, while I was writing this issue. Still no plugins, version is git-Yatopia-"aca39ae" 1.16.1 JDK8.

**Comment by MrIvanPlays** [comment] 2020-08-29 10:06
Duplicate of #164

**Closed as completed by MrIvanPlays** 2020-08-29 10:06 UTC
