### ISSUE TITLE
enderman run into the water

### ISSUE THREAD

**Issue by Disguys** [tr7zw/YAPFA#138] opened 2020-08-21 11:26 UTC
**Expected behavior**
not run into the water

**Steps to reproduce (if known)**
video about the bug - https://youtu.be/BKf2vQFamkI

**Installed plugins**
https://imgur.com/a/7XQXNL6

**Version**
git-Yatopia-"483c794" (MC: 1.16.2)

**Comment by MrIvanPlays** [comment] 2020-08-21 11:28
report to paper, this is from their pathfinder optimizations.
it may be vanilla too, but this is low chance.

**Comment by Disguys** [comment] 2020-08-21 11:44
I left a report - https://github.com/PaperMC/Paper/issues/4165

**Comment by kennytv** [comment] 2020-08-21 12:33
Stop forwarding people to create issues somewhere if you haven't tested their validity/origin for yourself. This is a Vanilla issue.

**Comment by MrIvanPlays** [comment] 2020-08-21 12:43
I forward them whenever I see there isn't a patch modifying the behavior of the reported thing.

**Comment by kennytv** [comment] 2020-08-21 12:46
Then don't do that please, it's evidently a faulty approach... Tell people to actually **test** if the problem persists on Paper/Spigot/Vanilla and don't just plainly, _very_ confidently say "report to paper, this is from their pathfinder optimizations."

**Comment by MrIvanPlays** [comment] 2020-08-21 12:49
ok
accidental close

**Comment by MrIvanPlays** [comment] 2020-08-21 16:29
We may fix this, although it is a low priority since it isn't something game breaking.

**Comment by toinouH** [comment] 2020-08-21 16:37
I think this the bug: https://bugs.mojang.com/browse/MC-185977

**Comment by Titaniumtown** [comment] 2021-01-24 22:12
Can this still be reproduced on the latest build?

**Comment by Titaniumtown** [comment] 2021-01-29 17:07
I'm going to close this issue. Feel free to reopen it, if it can still be reproduced.

**Comment by Disguys** [comment] 2021-02-06 00:12
However, after checking this error on the latest version of Yatopia, I made sure that it is still relevant, I apologize in advance for such a long answer.

**Comment by Disguys** [comment] 2021-02-06 00:12
I think that this problem should be opened again

**Comment by ishland** [comment] 2021-02-06 01:07
If you still have this issue, feel free to open a new issue.

**Closed as completed** 2021-02-06 15:18 UTC
Labels: bug, low priority, vanilla
